### ISSUE TITLE
ftplib api

### ISSUE THREAD

**Issue by jettify** [pohmelie/aioftp#12]
What do you think about adding *ftplib* like api? (https://github.com/python/cpython/blob/master/Lib/ftplib.py)

So basically, create separate class or client, with api same as in *ftplib* but ``await`` or ``yield from`` added. People familiar with sync version of *ftplib* will pick up new async api easily.  Such approach will simplify porting apps from sync to async too.

Porting ftplib should be strait forward, I can help with review and and may be code.

**Comment by pohmelie** [comment]
When I started with aioftp I was just copy ftplib features, and you can see it: callbacks, blocks_size, timeouts, rest, etc. But time goes by and I'm sure, now we have much better api: streams (btw your great idea), high level paths operations (upload, download), high level listing of directory, recursive remove and so on, but also we have access to any level of abstraction (from lowest to highest with grades) if we need something special.
(Also I don't like short names like mkd, mlsd, rmd, cwd, pwd, etc. But it's my problem, cause someone definetly like it. :stuck_out_tongue_closed_eyes: )
But probably you are right, and we can do ftplib-like api. But as a subpackage:
```python
import aioftp.ftplib

# and here we have old-good-api
```
What do you think about subpackage?

**Comment by jettify** [comment]
Oh I see, I've missed callbacks thing there... Better not to mix callbacks and asyncio at all...

**Comment by jettify** [comment]
Looks like callbacks used whenever we read data by chunks, so we can convert callbacks api to async iterator api:
```python
async for chunk in ftp.retrbinary(cmd, block=1024):
    print(chunk)
```

**Comment by pohmelie** [comment]
if so we should drop 3.4 and this will be not ftplib api, I think.

**Comment by jettify** [comment]
Hm, may be ftplib is no that good idea... I just tried to find a way to get
rid of callbacks without braking backwards compatibility.
