### ISSUE TITLE
Avoid possible races in acquire/release

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#13]
Semaphore-like object for counting connections and reject connections after some count acquired in ["greeting"](https://github.com/pohmelie/aioftp/blob/master/aioftp/server.py#L938-L939) and ["user"](https://github.com/pohmelie/aioftp/blob/master/aioftp/server.py#L975-L976) functions and released in ["finally" part of "dispatcher"](https://github.com/pohmelie/aioftp/blob/master/aioftp/server.py#L612-L618). But I think there is possibility that exception will be raised between setting connection.user/connection.acquired and real acquire() call. In this case semaphore-like object will be released without acquiring and the counter will be broken. So acquire should be atomic, but how to implement this? :confused:

**Comment by pohmelie** [comment]
Or there is no races, because between marking "acquired" and real acquire there is no context switch.
```python
import asyncio
import time


@asyncio.coroutine
def foo():

    print("entering foo")
    task = loop.create_task(bar())
    asyncio.async(task)
    yield from asyncio.sleep(1)
    print("canceling")
    task.cancel()
    print("raising")
    raise Exception("foobar")


@asyncio.coroutine
def bar():

    d["x"] = True
    print(d)
    time.sleep(2)
    d["y"] = True
    print(d)


d = {}
loop = asyncio.get_event_loop()
try:

    loop.run_until_complete(foo())

finally:

    print(d)
```
```
entering foo
{'x': True}
{'y': True, 'x': True}
canceling
raising
{'y': True, 'x': True}
Traceback (most recent call last):
  File "/home/broomrider/pro/py/aioftp/tmp.py", line 32, in <module>
    loop.run_until_complete(foo())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/broomrider/pro/py/aioftp/tmp.py", line 15, in foo
    raise Exception("foobar")
Exception: foobar
```

**Comment by rsichny** [comment]
if you want to be 100% sure that it is atomic - just lock it:

```python
connection.acquired_lock = asyncio.Lock(loop=loop)
```

```python
def greeting(self, connection, rest):
    ...
    with (yield from connection.acquired_lock):
            connection.acquired = True
            self.available_connections.acquire()
    ...
```

```python
def dispatcher(self, reader, writer):
    ...
    with (yield from connection.acquired_lock):
        if connection.acquired:
            self.available_connections.release()
```

**Comment by pohmelie** [comment]
Lock have nothing for my question (it was bad explained I think).
If we are on "greeting" and then someone cancel our coroutine:
```python
def greeting(self, connection, rest):
    ...
    connection.acquired = True
    # interrupt here and code below will never executed
    self.available_connections.acquire()
```
Or, as I think right now, it is impossible to cancel working (not waiting) coroutine. Am I right?

**Comment by rsichny** [comment]
ok, i actually misunderstood the problem. You're right, running coroutine can not be cancelled, so until there's no `yield from` somewhere between two calls - you're safe

**Comment by pohmelie** [comment]
Awesome!
