### ISSUE TITLE
Execute blocking calls in threadpool

### ISSUE THREAD

**Issue by jettify** [pohmelie/aioftp#15]
Client makes blocking calls for reading files. It could be an issue if file system is slow. So this calls should be executed using ``loop.run_in_executor``. Or may be you may want to use ``aiofiles`` to handle files.

One of several places:
https://github.com/pohmelie/aioftp/blob/master/aioftp/client.py#L757

**Comment by pohmelie** [comment]
You are right. More accurate, this is not only "files" operations, but "paths" (remove dir, rename file, move file, etc.) and aiofiles do not cover all needs. Server have [abstraction layer](http://aioftp.readthedocs.org/path_io_api.html) for this. So we should just intergate path-io, I think.
Why it was not done yet? I don't know :laughing:

**Comment by jettify** [comment]
btw, could you release new version with streaming? (and create git tag?)

**Comment by pohmelie** [comment]
Do you think it is a good time to release? There is couple of things I want to do before:
* server throttle
* add AsyncPathIO to client
* remake tutorials in documentation
What do you think?

**Comment by jettify** [comment]
It is big not issue for me, but minor library release  with streaming api would be helpful. For now I forked aioftp just to freeze its current state, and will switch to pypi as soon as release available.

**Comment by pohmelie** [comment]
Tag and pypi release added.

**Comment by jettify** [comment]
Thanks a million! I have already updated my requirements and tested new release.
