### ISSUE TITLE
Move timeouts to pathio

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#17]
What do you think about moving path timeouts to pathio? This will simplify the server and client (since pathio will be used in client too) code. What is better:
* use timeout per method, as keyword argument?
* use timeout per instance, as initialization argument?

Second looks more elegant.
Also, definetly there is place for decorator.

**Comment by rsichny** [comment]
my vote is for make it an init param, and change all the calls like `yield from asyncio.wait_for(connection.path_io.is_dir(path), connection.path_timeout, loop=connection.loop)` in Server to simple `yield from connection.path_io.is_dir(path)`

**Comment by pohmelie** [comment]
Yeah, when I created this issue I thought same. But pathio is kind-like user space code. I mean pathio is positioned as an extensible (via inherritance) implementation of path operations, so should we bring those timeouts to user? This will reduce the core «power», «stability», «centralization» (I don't know right words here). Btw, same with user manager.

**Comment by rsichny** [comment]
user might not want to actually timeout path operations for some reason - you could just provide with_timeout() decorator so he could decide whether to use it or not in his implementation.
Actually you can even make something like http://ideone.com/JwhxvP and use it in any object, why not.

**Comment by pohmelie** [comment]
@rsichny you beat me, I think about same right now :smile:

**Comment by pohmelie** [comment]
Also, I think there should be no `timeout` argument check in decorator and it should be crashed, since this can help when debugging and prevent error when user think it is with timeout, but it actually not.
```python
def with_timeout(f):

    @functools.wraps(f)
    def wrapper(cls, *args, **kwargs):

        coro = f(cls, *args, **kwargs)
        return asyncio.wait_for(coro, cls.timeout, loop=cls.loop)

    return wrapper
```

**Comment by rsichny** [comment]
my code was just a quick example, if you think AttributeError is correct behavior - go for it, it might be really better solution to fail then silently ignore the decorator ;)
