### ISSUE TITLE
upload sources to PyPI

### ISSUE THREAD

**Issue by rsichny** [pohmelie/aioftp#18]
https://docs.python.org/3.5/distutils/packageindex.html#package-index

basically you just run `python setup.py sdist upload`

**Comment by pohmelie** [comment]
Done.

**Comment by rsichny** [comment]
thanks!
ps. you can actually drop flit now and simply use "python setup.py sdist bdist_wheel upload" i think ;)

**Comment by pohmelie** [comment]
I will try it out with next release :+1:
