### ISSUE TITLE
Double USER message

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#23]
Should we handle USER, PASS commands after user logged in? What should we do:
* error code (which one?)
* disconnect + error code
* ignore

**Comment by rsichny** [comment]
according to RFC "Servers may allow a new USER command to be entered at any point in order to change the access control and/or accounting information"

**Comment by rsichny** [comment]
regarding PASS - "This command must be immediately preceded by the user name command", so if PASS is not preceeded by USER server should return 503

**Comment by pohmelie** [comment]
Hm, ok. Think to think a little bit.

**Comment by pohmelie** [comment]
I think it is done.
