### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by deme-rs** [pohmelie/aioftp#25]
At least because of the following:
1. **Passive mode doesn't work.** v0.1.7 has introduced a new default host, because binding to 0.0.0.0 was troublesome for pasv; however, the change was done in *\_\_main\_\_.py*, and *setup.py test* sets up the server directly, without calling *\_\_main\_\_*; therefore, on Windows, when running nosetests, the server binds to 0.0.0.0 and the client can't connect to the returned socket address
2. **The client (non-posix) requests file on paths that the server (posix behaviour) doesn't understand**; for example, in *test-file.test_download_folder*, the client asks for *MLST \server*, which is non-posix; the server thinks the path doesn't exist, because it's looking for a posix path

**Comment by pohmelie** [comment]
First one is fixed. Second one will be fixed as soon as possible. Same problem was on server side, virtual paths should be PurePosixPath, so it sounds easy. Thanks for issue :+1:

**Comment by pohmelie** [comment]
Fixed, but looks like there is problem with throttle. Will be closed after.

**Comment by pohmelie** [comment]
Throttle fixed, all tests are passed on windows.
