### ISSUE TITLE
ABOR(T) races

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#29]
I think there can be races with "workers" and ABOR command. Flow:
1. Worker running.
=== schedule ===
2. Worker store positive (2xx) result to response queue.
3. Worker done.
=== schedule ===
4. abor function called and worker still in extra_workers.
5. abor store 4xx and 2xx to queue.

What client see:
```
2xx - ok done
4xx - aborted
2xx - aborted successful
```
I think FTP protocol is made without this in mind. This is not just server, but client issue also.
How to abort transmission properly?

**Comment by pohmelie** [comment]
After some reading of asyncio source of `asyncio.wait`, I realized, that after work done it is marked as done future with callback and always will be in done set and removed from extra. So, server side looks good. But client side…
For download we have situation, when we can't get socket state. Is socket closed by abort and we should not finish stream, and if we are done clearly and we should call finish. For example:
```python
import asyncio
import logging

import aioftp


async def yoba():

    PORT = 8888
    server = aioftp.Server(write_speed_limit=1024)
    client = aioftp.Client()

    async def abort():

        await asyncio.sleep(1)
        print("requesting abort")
        await client.abort()
        print("abort done")

    await server.start("127.0.0.1", PORT)
    await client.connect("127.0.0.1", PORT)
    await client.login()
    asyncio.ensure_future(abort())

    stream = await client.download_stream("big-file")
    while True:

        block = await stream.read()
        print("received:", len(block))
        if not block:

            print("stream finish")
            await stream.finish()
            break

    client.close()
    server.close()
    await server.wait_closed()

if __name__ == "__main__":

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(message)s",
        datefmt="[%H:%M:%S]",
    )
    loop = asyncio.get_event_loop()
    loop.run_until_complete(yoba())
```
```
RuntimeError: readline() called while another coroutine is already waiting for incoming data
```
Cause both, `abort` and `finish` trying to read from command connection.
One way is change `abort` behaviour. Abort will not wait for response, then we will get status code error in `finish`.

But upload flow is slightly different:
```python
import asyncio
import logging

import aioftp


async def yoba():

    PORT = 8888
    server = aioftp.Server(read_speed_limit=1024)
    client = aioftp.Client()

    async def abort():

        await asyncio.sleep(1)
        print("requesting abort")
        await client.abort(wait=False)
        print("abort done")

    await server.start("127.0.0.1", PORT)
    await client.connect("127.0.0.1", PORT)
    await client.login()
    asyncio.ensure_future(abort())

    stream = await client.upload_stream("tmp.bin")
    for _ in range(100):

        await stream.write(b"-" * 1024)
        await asyncio.sleep(0.2)
        print("write")

    print("stream finish")
    await stream.finish()

    client.close()
    server.close()
    await server.wait_closed()

if __name__ == "__main__":

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(message)s",
        datefmt="[%H:%M:%S]",
    )
    loop = asyncio.get_event_loop()
    loop.run_until_complete(yoba())
```
```
BrokenPipeError: [Errno 32] Broken pipe
```
How to unify abort reaction for both? And what about situation, when we "have nothing to abort"?

**Comment by rsichny** [comment]
These are not only abort races - guess you will get same errors when try to download/upload two files (or do whatever else) at the same time. This is not simply allowed by FTP and anyone who uses client should realize that even if the client itself is async, operations within one session should be performed sincronously. IMO both cases are incorrect usage of client and you shouldn't bother about fixing it.

**Comment by pohmelie** [comment]
@rsichny, yes, but abort is special case. It was introduced to interrupt data flow. And, I agree with you, on stream level it's ok to ignore this. But for high level aborting `upload` and `download` can corrupt the sequence of commands. So, maybe some synchronization?

**Comment by rsichny** [comment]
well, when aborting client should stop all the interactions on data connection, i'm not sure if you really need to handle this ot the end user should do it himself

**Comment by pohmelie** [comment]
@rsichny high level api made as sequence of low level, so I think we can't abort at any time (between data transfer there is next STOR command, for example). In this case end user can't do this, I think.

**Comment by pohmelie** [comment]
Today I've found something new in this problem. «Out-of-band» thing:
https://github.com/python-git/python/blob/master/Lib/ftplib.py#L228-L238
http://www.gnu.org/software/libc/manual/html_node/Out_002dof_002dBand-Data.html
http://www.programcreek.com/python/example/20884/socket.MSG_OOB
This can be aplied at client, but what about server? I've found nothing with «asyncio out of band» request. How deep is this and will client/server work with all this «third» client and servers? Is this only ABOR behaviour? FTP RFC have no out-of-band description at all. This make me sad.
Also https://github.com/jquast/telnetlib3 implement «out-of-band» message. But it is client-side.

**Comment by rsichny** [comment]
iirc OOB is tcp flag - it just means the highest priority for message to be sent. I don't think we should ever go this deep into protocol. And iirc server will handle it correctly with regular recv() (though i might be wrong here)
