### ISSUE TITLE
server should accept data connection after service command and not only before

### ISSUE THREAD

**Issue by rsichny** [pohmelie/aioftp#3]
Currently this scenario, which is actually correct, can not be handled by server:
```
Command:	PASV
Server: start listening to 0,0,0,0,215,187
Response:	227-listen socket created
Response:	227 (0,0,0,0,215,187)
Command:	STOR test.wav
Client: connect to 0,0,0,0,215,187
Response:	150 data transfer started
Response:	226 data transfer done
```

I suppose to disable `ConnectionConditions.passive_connection_made` check on service commands and add a possibility to wait for data connection during some time after service command call (in https://github.com/pohmelie/aioftp/blob/master/aioftp/server.py#L1020 for example). If this is ok i'll provide a patch.

**Comment by pohmelie** [comment]
I know about this issue, but I don't think this is correct scenario. RFC have no information about order of connections and commands (or I've just missed it). From my point of view "action" before "channel" is error.

**Comment by rsichny** [comment]
there're some mentions, for example:

"The server, upon receiving the transfer request, will initiate the data connection to the port.  When the connection is established, the data transfer begins between DTP's, and the server-PI sends a confirming reply to the user-PI."

"The user-PI may then send the corresponding service commands to A and B.  Server B initiates the connection and the transfer proceeds."

PS. Actually my only argument for getting it fixed is that this is filezilla behavior.

**Comment by pohmelie** [comment]
Unfortunatelly it's not only filezilla behavior…
Anyway, I think we should not remove current decorators, but modify. We can deal with some "timeout" argument for ConnectionConditions (and, if we need in future with others). So we can deal with different timeouts for different conditions just splitting them to two decorators (for example).
```python
class ConnectionConditions:

    def __init__(self, *fields, timeout=0):

        self.fields = fields
        self.timeout = timeout

    def __call__(self, f):

        @asyncio.coroutine
        @functools.wraps(f)
        def wrapper(cls, connection, rest, *args):

            @asyncio.coroutine
            def waiter():

                for name, message in self.fields:

                    while name not in connection:

                        yield from asyncio.sleep(0.1, loop=loop)

            loop = connection["loop"]
            try:

                yield from asyncio.wait_for(waiter(), self.timeout, loop=loop)

            except TimeoutError:

                template = "bad sequence of commands ({})"
                return True, "503", str.format(template, message)

            return (yield from f(cls, connection, rest, *args))

        return wrapper

```

I didn't test this code at all, but I think the idea is clear. If you think you have better solution or this solution is not so good as I thinking about please comment.

**Comment by rsichny** [comment]
i was thinking to put something like this to methods' body, but you're right, decorators should work too - will try and get back with patch

**Comment by rsichny** [comment]
https://github.com/pohmelie/aioftp/pull/4

**Comment by pohmelie** [comment]
Futures is good idea, anyway. I don't like both solutions: mine and yours. Mine, because of constant sleep. Yours, because of not uniform "connection" values. Some are just "values" and we just get them by key, but some are futures and we need result.
I think we need to reimplement "dict" for connection state storage. I made some dirty solution/presentation:
https://gist.github.com/pohmelie/084542a37e916eecf7eb
http://ideone.com/uloQXP
As you can see we can wait in decorator with futures and don't think about "result" in foo/bar/baz. I think it's pretty nice. But maybe I missed something in implementation (especially of iter and len). Your comments are strictly welcome :wink:

**Comment by rsichny** [comment]
i don't like the fact that connection is a dict at all tbh and it seems to be not the bad idea to implement Connection class instead of using plain dict.

**Comment by rsichny** [comment]
and regarding your example - if i got your idea right, you want basically the same thing i did to be implemented for all conditions and not only for "passive_connection_made" (i.e. to keep a set of futures to be resolved before next command is called), right?

**Comment by pohmelie** [comment]
Why dict is bad? We don't need any functions to deal with data. So what is profit? The only reason (maybe) is to remove unpack_keywords…
Yeah, you right, pretty same. And "functional" functions (pasv, stor, user…) will know nothing about timeouts and "future" nature of connection values.

**Comment by rsichny** [comment]
i'm looking forward to implement active mode, in this case we can not establish data connection before service command is sent by client, so basically we'll need to do something like
`reader, writer = yield from connection.pop('passive_connection')` anyway in stor, retr, list, etc.

Also something like
```
with (yield from connection.get_data_connection()) as (reader, writer):
```
is a bit more self-describing, then
```
data_reader, data_writer = connection.pop("passive_connection")
with contextlib.closing(data_writer) as data_writer:
```
don't you think so?

**Comment by pohmelie** [comment]
I'm really don't know why we need active mode. Almost no one (I think) use active mode (server -> client), cause NAT. RFC case when we manage two servers and move files between them directly is based on ancient bandwidth limitation. What is the usecase of active mode?
Also, if we will do active mode, then there is a lot of work for re-thinking and refactoring, cause current model is passive-oriented. Aioftp was designed as minimal as possible in mind, and there is really no reasons to use active mode. As LIST for example, but so huge amount of clients don't use MLSD/MLST. As TYPE, cause nobody will use ftp "by hands" nowadays… but legacy. And in context of above: why we need active? Someone use it? We get something extraordinary with active? I think no.
About with: until 3.5 (13 september btw) you can't do  asynchronous in context manager (so you can't close writer), but if we will, then we break compatibility with 3.4. Or you mean generate non-async contextmanager and return it from get_data_connection?

**Comment by rsichny** [comment]
actually i did active mode in like 10 lines of ugly code so i'd not say it's hard to do. And yes, unfortunately active mode is still is used, and since there're no async ftp server libraries for 3.4+ (twisted ftp isn't migrated to python3 yet) i'd say active mode should be supported just in case someone needs it.

regarding context managers - here's a quick and dirty example: http://ideone.com/0se91r

**Comment by pohmelie** [comment]
Ok, if you think active mode is easy to do… Probably we need to introduce "mode" connection state and rename "passive_connection" to "data_connection" to make it more uniform. So STOR, RETR, MLSD will know nothing about connection nature (direction) and this is good. And we need one more decorator :grin: for actual connection establishment/waiting (for active/passive mode). And, yeah, we can use class-container instead of dict, but this will affect only presentation and handling:
connection["data_connection"] -> connection.data_connection
"data_connection" in connection -> connection.data_connection [is None]
connection.pop("data_connection") -> connection.data_connection = None
But I vote for hiding futures from STOR, RETR, etc. functions. So they will deal with data, that already exists (data_connection) and don't wait it. What do you think?

**Comment by rsichny** [comment]
with the changes from #4 this just works (of course after removing ConnectionConditions.passive_server_started check for service commands):
```python
    @aioftp.server.ConnectionConditions(aioftp.server.ConnectionConditions.login_required)
    @aioftp.unpack_keywords
    @asyncio.coroutine
    def port(self, connection, addrinfo, *, loop):

        if "passive_server" in connection:
            connection.pop("passive_server").close()

        if "passive_connection" in connection:
            connection.pop("passive_connection").cancel()

        ip, port = parse_address_response(addrinfo)

        class _cm:

            def __init__(self, connection):
                self.connection = connection

            @asyncio.coroutine
            def connect(self):
                return (yield from open_connection(ip, port, loop, loop.create_connection))

            def __iter__(self):
                reader, writer = yield from self.connect()
                return (reader, writer)

        connection["passive_connection"] = _cm(connection)

        return True, '200', 'PORT command successful.'
```

**Comment by pohmelie** [comment]
Oh, yeah, about context managers. Yes, I mean same as your code.

**Comment by pohmelie** [comment]
**rsichny**, please take a look at [new branch](https://github.com/pohmelie/aioftp/tree/feature/connection-state-with-futures), which implements possibility to "wait for PASV, PORT". Because before, since dispatcher architecture, we can't do so (we saw "STOR" and went to the Server.stor coroutine and wait for data connection/return error, but if we wait, then we block the command connection reader. Dispatcher was built sequent).
But now it have real dispatch work with [asyncio.wait](https://github.com/pohmelie/aioftp/blob/feature/connection-state-with-futures/aioftp/server.py#L482). I've tested it on FileZilla, but looks like it send PASV before STOR/LIST/RETR. But two new [tests](https://github.com/pohmelie/aioftp/blob/feature/connection-state-with-futures/tests/test-timeouts.py#L48) works well.
Also [connection](https://github.com/pohmelie/aioftp/blob/feature/connection-state-with-futures/aioftp/server.py#L142) is future-based, inherits from defaultdict and have "magic" methods for transparency.
What do you think? :blush:

**Comment by rsichny** [comment]
seems like test is actually incorrect...
Correct test sequence would be the next:
1. client send PASV
2. client send STOR
3. client opens data connection

Instead you have:
1. client send STOR
2. client send PASV
3. client opens data connection

The first one should work, the second should lead to 503 after step 2

**Comment by rsichny** [comment]
sorry, not 503, but a sequence of 150, then 426 replies

**Comment by pohmelie** [comment]
Hm, you are right! Hopefuly this is pretty easy to change… I will comeback soon.

**Comment by pohmelie** [comment]
Don't get why not 503?

**Comment by rsichny** [comment]
>sorry, not 503, but a sequence of 150, then 426 replies right after STOR

**Comment by pohmelie** [comment]
I think it's done, but no deal with 150-425. Still 503, since we don't determine "classes" of ConnecionConditions, it is just check the rules and can return some lines… if they are the same for all: user_required, login_required, passive_server_started, data_connection_made, rename_from_required… or we just need to expand description with return codes?

**Comment by rsichny** [comment]
guess yes you could add response parameter for decorator and decorate stor_worker() instead of stor() itself, like this:
```python 
    @ConnectionConditions(
        ConnectionConditions.login_required,
        ConnectionConditions.passive_server_started)
    @PathPermissions(PathPermissions.writable)
    @asyncio.coroutine
    def stor(self, connection, rest, mode="wb"):

        @ConnectionConditions(ConnectionConditions.data_connection_made, wait=True, fail_response="426")
        @asyncio.coroutine
        def stor_worker():
```

**Comment by pohmelie** [comment]
Oh, awesome idea! :thumbsup:

**Comment by rsichny** [comment]
btw, after pulling the last changes i'm getting this sometimes (had no time to research yet) :
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "<...>aioftp/server.py", line 527, in dispatcher
    if not connection.loop.is_closed():
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'is_closed'
```

**Comment by rsichny** [comment]
actually same in tests:
```
$python --version
Python 3.4.0
$ python run-tests.py 
Testing AsyncPathIO
...F
======================================================================
FAIL: test-connection.test_closing_pasv_connection
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/nose/tools/nontrivial.py", line 97, in newfunc
result = func(*arg, **kw)
File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/nose/tools/nontrivial.py", line 67, in newfunc
raise AssertionError(message)
nose.proxy.AssertionError: test_closing_pasv_connection() did not raise ConnectionRefusedError
-------------------- >> begin captured logging << --------------------
''[17:08:49]:' aioftp server: serving on 0.0.0.0:8888'
''[17:08:49]:' aioftp server: new connection from 127.0.0.1:56414'
''[17:08:49]:' aioftp server: 220 welcome'
''[17:08:49]:' aioftp client: 220 welcome'
''[17:08:49]:' aioftp client: USER anonymous'
''[17:08:49]:' aioftp server: USER anonymous'
''[17:08:49]:' aioftp server: 230 anonymous login'
''[17:08:49]:' aioftp client: 230 anonymous login'
''[17:08:49]:' aioftp client: TYPE I'
''[17:08:49]:' aioftp server: TYPE I'
''[17:08:49]:' aioftp server: 200 '
''[17:08:49]:' aioftp client: 200'
''[17:08:49]:' aioftp client: PASV'
''[17:08:49]:' aioftp server: PASV'
''[17:08:49]:' aioftp server: 227-listen socket created'
''[17:08:49]:' aioftp server: 227 (0,0,0,0,156,21)'
''[17:08:49]:' aioftp client: 227-listen socket created'
''[17:08:49]:' aioftp client: 227 (0,0,0,0,156,21)'
''[17:08:49]:' aioftp client: QUIT'
''[17:08:49]:' aioftp server: QUIT'
''[17:08:49]:' aioftp server: 221 bye'
''[17:08:49]:' aioftp server: closing connection from 127.0.0.1:56414'
''[17:08:49]:' Future/Task exception was never retrieved
future: Task(<dispatcher>)<exception=AttributeError("'_UnixSelectorEventLoop' object has no attribute 'is_closed'",)>'
Traceback (most recent call last):
File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
result = coro.send(value)
File "/home/roman/workspace/aioftp/aioftp/server.py", line 527, in dispatcher
if not connection.loop.is_closed():
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'is_closed'
''[17:08:49]:' Future/Task exception was never retrieved
future: Task(<response_writer>)<exception=TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'",)>'
Traceback (most recent call last):
File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
result = coro.send(value)
File "/home/roman/workspace/aioftp/aioftp/server.py", line 440, in response_writer
socket_timeout=connection.socket_timeout
File "/home/roman/workspace/aioftp/aioftp/server.py", line 357, in write_response
yield from write(code + " " + tail)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
''[17:08:49]:' aioftp client: 221 bye'
''[17:08:49]:' Future/Task exception was never retrieved
future: Task(<parse_command>)<exception=ConnectionResetError()>'
Traceback (most recent call last):
File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
result = coro.send(value)
File "/home/roman/workspace/aioftp/aioftp/server.py", line 389, in parse_command
raise ConnectionResetError
ConnectionResetError
--------------------- >> end captured logging << ---------------------

Name            Stmts   Miss  Cover   Missing
---------------------------------------------
aioftp              8      0   100%
aioftp.client     294    146    50%   31-39, 110-111, 141-145, 167, 237-267, 279-295, 353-365, 376-378, 390-398, 413-426, 438, 458-497, 512-514, 525-526, 537-538, 552-557, 572-573, 585, 598-613, 666, 703-743, 803-850, 920, 977, 985, 998
aioftp.common       7      0   100%
aioftp.errors      12      4    67%   39-49
aioftp.pathio     245    162    34%   41, 55, 69, 84, 96, 108, 122, 138, 155, 169, 182, 193, 208, 219, 224, 229, 234, 239, 244, 249, 254, 259, 264, 269, 274, 279, 292, 302, 307-308, 313, 318, 323-327, 332, 348-349, 359-360, 367-371, 375, 405-406, 410, 414-432, 437, 442-443, 448-449, 454-494, 499-521, 526-544, 549-558, 563-578, 589-632, 637-638, 643, 648, 653-678
aioftp.server     530    159    70%   60-62, 66, 107, 131, 187, 207, 231, 342-348, 435, 511, 519-520, 529-540, 545, 620-623, 672-673, 718-719, 799, 806, 832-835, 839-840, 850-860, 869-880, 892-894, 904-907, 913-914, 922-929, 939-946, 951-983, 994-1022, 1027-1057, 1068-1097, 1105-1108, 1116-1119, 1129-1139, 1149-1156, 1187-1188, 1227, 1264-1265, 1308, 1340, 1366
---------------------------------------------
TOTAL            1096    471    57%
----------------------------------------------------------------------
Ran 4 tests in 2.377s

FAILED (failures=1)
Traceback (most recent call last):
  File "run-tests.py", line 40, in <module>
    _out=lambda line: print(str.strip(line)),
  File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/sh.py", line 486, in __init__
    self.wait()
  File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/roman/workspace/aioftp/env/lib/python3.4/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: "/home/roman/workspace/aioftp/env/bin/nosetests --exclude=run-tests.py --stop --no-byte-compile --with-coverage --cover-package=aioftp --logging-format='%(asctime)s %(message)s' --logging-datefmt='[%H:%M:%S]:' --logging-level=INFO"

  STDOUT:


  STDERR:

```

**Comment by pohmelie** [comment]
[is_closed](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_task#asyncio.BaseEventLoop.is_closed) new in 3.4.2. Maybe you have older version of python?

**Comment by pohmelie** [comment]
@rsichny, can you confirm, that current code works fine with delayed connections to close this issue?

**Comment by rsichny** [comment]
yes, checked with 3.4.3 and 3.5 - seems like all is ok, closing this one. thanks

**Comment by pohmelie** [comment]
@rsichny btw, it will be great if you will follow the project and help to make it better. I've created some issues right now, and I want you to take a look. If you have time and interest of course.

**Comment by rsichny** [comment]
@pohmelie be sure i will ;)
