### ISSUE TITLE
storing traceback to user

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#30]
What about to store traceback to user instead of just fall down and disconnect? Something like:
```
4xx-python error
4xx-in file...
4xx-line this
4xx-foo bar
4xx done
```

**Comment by rsichny** [comment]
exposing this data to user is potentially dangerous - it would be better idea to log everything correctly (instead of writing to stderr).

**Comment by pohmelie** [comment]
@rsichny, do you mean «log» as standard python logging or proper ftp errors to user?

**Comment by rsichny** [comment]
as standart python logging

**Comment by pohmelie** [comment]
https://github.com/pohmelie/aioftp/commit/59161c73ec13af9a2d3a2a862ab5c92ce56cea3d
