### ISSUE TITLE
Exception during upload_stream causes hang

### ISSUE THREAD

**Issue by heftig** [pohmelie/aioftp#41]
This hangs:
```python
from aioftp import ClientSession
import asyncio

async def main():
    async with ClientSession("localhost") as client:
        async with client.upload_stream("/foo/bar") as stream:
            raise RuntimeError()

asyncio.get_event_loop().run_until_complete(main())
```

This does not:
```python
from aioftp import ClientSession
import asyncio

async def main():
    async with ClientSession("localhost") as client:
        async with client.upload_stream("/foo/bar") as stream:
            try:
                raise RuntimeError()
            finally:
                stream.writer.write_eof()

asyncio.get_event_loop().run_until_complete(main())
```

Apparently, without the `write_eof`, the data connection doesn't get closed.

In `ClientSession.__aexit__` aioftp sends a `QUIT` but there's no reaction from the server until the data connection has been closed.

My guess is you should add the `write_eof` to `DataConnectionThrottleStreamIO.__aexit__`.

Tested against a local `vsftpd`.

**Comment by heftig** [comment]
Interestingly, if you `pass` instead of `raise`, it works fine.

I wonder what's going on. The code paths seem to be the same since neither `__aexit__` is actually interested in the exception.

**Comment by pohmelie** [comment]
@heftig, probably something differs at flushing `quit`, so on raise there is no real data transfer.
> add the `write_eof` to `DataConnectionThrottleStreamIO.__aexit__`

This definitely should be there, thanks! :+1:

**Comment by heftig** [comment]
>The code paths seem to be the same since neither __aexit__ is actually interested in the exception.

Strike that; `DataConnectionThrottleStreamIO.__aexit__` doesn't call `finish` if there's an exception. As a result, `close` doesn't get called either, and the connection stays open.

So `write_eof` was a red herring, and it was really the missing `close`.

I guess since every `write` on the stream does a `drain`, `write_eof` isn't needed?

**Comment by heftig** [comment]
AFAIK normally to close a connection you `write_eof`, then `await drain` and then `close`, to ensure all bytes have been sent.

**Comment by pohmelie** [comment]
It looks like `writer.close()` is enough here. Since `write_eof` closing only writing, but you can still read (as documentation said). Also, not all transports support `write_eof`.
Is it enough?
``` python
async def __aexit__(self, exc_type, exc, tb):

        if exc is None:

            await self.finish()

        else:

            self.close()
```

**Comment by heftig** [comment]
Yes, that works too, thanks.
