### ISSUE TITLE
Support NLST and/or LIST for servers without MLST/MLSD

### ISSUE THREAD

**Issue by jw4js** [pohmelie/aioftp#47]
ftp.gnu.org for instance doesn't support MLSD. Maybe make an attempt to parse LIST output or provide an API for a LIST parser?

**Comment by pohmelie** [comment]
#39

**Comment by jw4js** [comment]
Looks like this is actually a common issue. I will implement a parser as a fallback. If you can provide more sample LIST outputs I'll try and implement them if I have time, for now. NLST can be used as a last resort fallback along with CWD to check file/dir.

**Comment by pohmelie** [comment]
As I see it, it is just like feeding legacy monster and we should knock to ftp servers devolopers heads. But if you think that you can implement this accurate, do it ;)

**Comment by rsichny** [comment]
@jw4js 
> provide more sample LIST outputs

the output is quite similar in all server implementations actually
https://github.com/pohmelie/aioftp/blob/master/aioftp/server.py#L1348
https://github.com/proftpd/proftpd/blob/master/modules/mod_ls.c#L784

**Comment by jw4js** [comment]
@pohmelie 
What should be done in the case of symlinks? Should the type be "link" and the source destination be in the info dictionary or should the type of whatever it's pointing to be used? I'm thinking to use "link" type, so no information is lost, but using whatever it's pointing to would be consistent with NLST/CWD since there is no way in that case to tell if it is a link or a file/dir.

**Comment by pohmelie** [comment]
@jw4js, I can't test it right now (I will do it tomorrow). As I can see, MLSD have only "file" and "dir" types.

**Comment by jw4js** [comment]
@pohmelie In the case of LIST output some ftp servers(such as ftp.gnu.org) also give the unix file type in the unix mode string, as in "lrwxr-xr--".

**Comment by pohmelie** [comment]
@jw4js, it looks like `link` type is non-standard (https://tools.ietf.org/html/rfc3659#section-7.5.1). And actually, who cares is it symlink or not in case of ftp? In case of download, I don't care, I need content. In case of upload I want to overwrite. And symlinks paths are system dependent (they can be absolute), but ftp file tree is «virtual».

**Comment by jw4js** [comment]
@pohmelie I will do as you say. We still have "unknown" types in the case of non-standard ftp servers exposing weird things such as character devices, block devices, Doors(Solaris), especially if the server was calling a library function to create the mode string without looking at the file type. I think we should just ignore these "files", what do you think?

**Comment by pohmelie** [comment]
Hm, don't really know what to do in this case right now… anyway we can change it later, when some feedback will be collected (or will not, if this situation is rarely present).

**Comment by pohmelie** [comment]
It look like a bug right now, since if `type` is not "file" or "dir", then `aiter` will return `None`. This check probably should be removed. What do you think?

**Comment by jw4js** [comment]
@pohmelie I will fix it

**Comment by jw4js** [comment]
@pohmelie In the case that we are unable to parse a LIST line, but we already returned previous file names and info dictionaries, what should be done? We can keep track of which file names we already returned but that sounds like a bad solution, or we can restart the listing with NLST/CWD but that may lead to bugs in the program using the library. How should it be implemented?

**Comment by pohmelie** [comment]
In case if command exists `MLSD`, `LIST`, `NLST` and parsing fails, then exception should be raised. Fallback code should go to next method exactly if we don't have previous command, not parsing breaks.
