### ISSUE TITLE
Lazy change directory

### ISSUE THREAD

**Issue by jw4js** [pohmelie/aioftp#51]
Don't CWD until needed(list; downloading file; get_current_directory; uploading file; rmdir etc.). Aggregate sequential CWD's without other commands in between into one CWD. Consider it?(If yes I will do it)

**Comment by pohmelie** [comment]
Don't get it, `CWD` don't used by library itself. Did you mean user calls to `change_directory`?

**Comment by jw4js** [comment]
@pohmelie Yes

**Comment by pohmelie** [comment]
This looks like overhead. Actually user don't need to use `CWD` for list, downloading, etc. So optimization at this level is useless, I think.

**Comment by jw4js** [comment]
I'm thinking that we implement CWD completely client side, avoiding CWD altogether. Consider it?

**Comment by pohmelie** [comment]
@jw4js, yes, actually no operation currently required `CWD` :wink:
