### ISSUE TITLE
Avoid logging FTP output as bytes

### ISSUE THREAD

**Issue by sametmax** [pohmelie/aioftp#52]
I recently had to open [a PR](https://github.com/crossbario/crossbar/pull/1001) to another project because of aioftp logging strategy.

Basically aioftp logs everything sent from the ftp serve into the logger. The good thing is it allowed me to make crossbar more robust. The bad thing is aioftp probably should not do that, underlying code has no way to know the bytes encoding and can't decode it cleanly.

It should always provide unicode strings to the logger, dealing the decoding before passing it to any other part of the system. This means finding out the charset, or mitigating errors if they happen while decoding with a default charset.

On a personal note, aioftp has been very helpful to me in a professional project, and I like to thank you for the work you put into it. It's currently helping a heavy transport facility to track all vehicles in France. 

Cheers !

**Comment by pohmelie** [comment]
I run over the client code and see only two points of logging:
https://github.com/pohmelie/aioftp/blob/master/aioftp/client.py#L188
https://github.com/pohmelie/aioftp/blob/master/aioftp/client.py#L268
Both are python strings, not bytes.

Or I misunderstood problem…

> On a personal note, aioftp has been very helpful to me in a professional project, and I like to thank you for the work you put into it. It's currently helping a heavy transport facility to track all vehicles in France.

Wow, nice to hear :wink:

**Comment by sametmax** [comment]
I see your point. I read quickly the code and couldn't find the source of the bytes either. The only thing I know is that:

- crossbar did receive a log with bytes and tried data.decode('utf8') and it crashed it.
- pdb revealed data was an FTP message
- doing logging.getLogger('aioftp.client').setLevel(logging.ERROR) stopped the problem

**Comment by pohmelie** [comment]
How crossbar receives logs? You redirect them? On which bytes `decode` breaks?

**Comment by sametmax** [comment]
The line is in the PR I linked. Crossbar received logs by 3 ways:

- the regular python logging
- the twisted logging facility
- capturing stdout

**Comment by pohmelie** [comment]
I still don't get where `aioftp` is broken... Actually I don't get why `aioftp` logging can break something.

**Comment by pohmelie** [comment]
Can you provide exactly case of bytes, which can't be decoded to string with "utf8" codec?

**Comment by pohmelie** [comment]
So… is it still a problem and is it belongs to `aioftp`?
