### ISSUE TITLE
please add sendfile support

### ISSUE THREAD

**Issue by yieyu** [pohmelie/aioftp#55]
I believe that it will get better performance with sendfile, and there is one implementation from [Tinche/aiofiles](https://github.com/Tinche/aiofiles/blob/master/aiofiles/os.py#L20)

**Comment by pohmelie** [comment]
1. It is OS dependent.
2. It is blocking (running executor is evil in this case, cause this will produce/use threads/processes on each send).
3. There are cases when one side don't know how much data should be received.

**Comment by pohmelie** [comment]
Of course, if you will implement this accurate and this will speed up interaction without problems, then it will be merged.

**Comment by yieyu** [comment]
Thanks for your reply, I'm not familiar with asyncio lib. I just wondering if it could have thread pool, then there may be a boost without too much modifications.

**Comment by pohmelie** [comment]
@yieyu 
Unfortunately, thread pool is opposite to asyncio idea. And, as I said before, sometimes we don't know how much data we will receive.

**Comment by yieyu** [comment]
I got it. Thank you for sharing your ideas
