### ISSUE TITLE
KeyError: 'ot'

### ISSUE THREAD

**Issue by bachya** [pohmelie/aioftp#58]
Hi there – I'm attempting to connect to a local FTP server on an IP camera and am getting the following stacktrace:

```
Task exception was never retrieved
future: <Task finished coro=<test() done, defined at test.py:13> exception=KeyError('ot',)>
Traceback (most recent call last):
    File "test.py", line 18, in test
      await client.list(path),
    File "/Users/abach/.local/share/virtualenvs/Downloads-ZJLnFE2W/lib/python3.6/site-packages/aioftp/common.py", line 120, in _to_list
      async for item in self:
    File "/Users/abach/.local/share/virtualenvs/Downloads-ZJLnFE2W/lib/python3.6/site-packages/aioftp/client.py", line 633, in __anext__
      name, info = cls.parse_line(line)
    File "/Users/abach/.local/share/virtualenvs/Downloads-ZJLnFE2W/lib/python3.6/site-packages/aioftp/client.py", line 378, in parse_list_line
      info["unix.mode"] = self.parse_unix_mode(s[1:10])
    File "/Users/abach/.local/share/virtualenvs/Downloads-ZJLnFE2W/lib/python3.6/site-packages/aioftp/client.py", line 308, in parse_unix_mode
      mode |= parse_rw[s[0:2]] << 6
KeyError: 'ot'
```

Here's the dummy app I built – seems like this stacktrace occurs with `client.list()`:

```python
async def test(path):
    async with aioftp.ClientSession('MY_HOST', 21, 'MY_USER, '') as client:
        await client.list()


loop = asyncio.get_event_loop()
tasks = [test()]
loop.run_until_complete(asyncio.wait(tasks))
loop.close()
```

For what it's worth, I'm able to connect to this server fine using Filezilla:

<img width="1280" alt="screen shot 2017-10-06 at 11 21 38 pm" src="https://user-images.githubusercontent.com/47216/31305033-33e643bc-aaed-11e7-8e85-7665f408411b.png">

Not sure what other info I can give you, but please let me know. I read [your comment about MLSD](https://aioftp.readthedocs.io/client_tutorial.html#warning); wondering if that's an issue here?

Appreciate your help!

**Comment by bachya** [comment]
After some more digging,  I can confirm that this server doesn't support the `MLSD` command; when I manually run `LIST` on my path, I get a layout that looks like this:

```
total X
drwxr-xr-x    2 root     root         32768 Oct  7 05:21 DIR1
drwxr-xr-x    2 root     root         32768 Oct  7 05:21 DIR2
```

I can also verify that this server is `ftpd` running on BusyBox.

**Comment by bachya** [comment]
One last nugget: after messing around with my own copy of your code, it looks like `parse_unix_mode` is trying to process that top line:

```
total 2144
```

More specifically, after that first `t` gets shifted off, the method attempts to parse `otal 2144`. So, that explains why it's looking for a key of `ot` in `parse_rw`.

As you note in the docs, I'm sure it's awful to have to parse the `LIST` command. I'll take a look through the code to see if I can figure out a fix, but I'm no expert, so I appreciate any feedback you can provide. Thanks again!

**Comment by pohmelie** [comment]
You're totally right. The reason is this first line. Possible solution is to skip lines, which can't be parsed. This is pretty easy to do (at first glance :thinking:):
https://github.com/pohmelie/aioftp/blob/master/aioftp/client.py#L633
``` python
try:
    name, info = cls.parse_line(line)
except KeyboardInterrupt:
    raise
except:
    continue
```
But I'm not sure about exceptions list… is it enough to raise only `KeyboardInterrupt` or there is another cases.

**Comment by bachya** [comment]
@pohmelie, your suggestion looks great to me. I don't think there's an exception other than `KeyboardInterrupt` that needs to be raised. I just implemented your suggestion and it works beautifully; would it be helpful if I submitted a PR, or would you like to handle it directly?

**Comment by pohmelie** [comment]
It will be awesome if you submit PR. I will release new version after.

**Comment by bachya** [comment]
Will do!
