### ISSUE TITLE
socket.send() raised exception

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/aioftp#7]
Sometimes, when trying to write to closed socket there is no `ConnectionResetError` exception, but some message to console "socket.send() raised exception" and program continue to execute as nothing happens. I don't understand the nature of this issue, but I saw same problem in stackoverflow questions. Here is code to reproduce, and this work on 3.4.2, 3.4.3 and 3.5.0 on my ubuntu 14.04:
```python
import asyncio
import time


host, port = "127.0.0.1", 8888
data_size = 8192


@asyncio.coroutine
def write_worker():

    reader, writer = yield from asyncio.open_connection(host, port)
    while True:

        writer.write(b"-" * data_size)
        yield from writer.drain()


def read_worker(reader, writer):

    start = time.perf_counter()
    while time.perf_counter() - start < 0.5:

        data = yield from reader.read(data_size)

    writer.close()


if __name__ == "__main__":

    try:

        loop = asyncio.get_event_loop()
        coro = asyncio.start_server(read_worker, host, port)
        server = loop.run_until_complete(coro)
        loop.run_until_complete(write_worker())

    except KeyboardInterrupt:

        server.close()

    print("done")
```
If we put `yield` between `writer.write(b"-" * data_size)` and `yield from writer.drain()` then problem go away, but we can't use yield in 3.5.0 with coroutines.
What to do:
* Left as is (:-1:)
* use `yield from asyncio.sleep(0)`
* something else?

**Comment by rsichny** [comment]
The weird thing is that problem goes away also in case if you put something like `print(data)` after `yield from reader.read(data_size)` or `yield from asyncio.sleep(0)` before closing writer in read_worker(). Tried to run server and client in different processes (just to avoid running in same loop) - mentioned changes in server code fixes the issue as well...

**Comment by pohmelie** [comment]
What a hell?! :smiley:
So you think it is enough to make some «magic» on server side? Cause I think anyone (client or server) can close connection, while another side will writing to socket.

**Comment by rsichny** [comment]
Idk honestly, but it feels like asyncio bug, "socket.send() raised exception" is the warning which, afaik, should never be encountered under normal circumstances.

**Comment by pohmelie** [comment]
https://github.com/python/asyncio/issues/248
https://github.com/python/asyncio/pull/257
@rsichny, you're right. That's asyncio issue.

**Comment by rsichny** [comment]
https://github.com/python/asyncio/pull/280

**Comment by pohmelie** [comment]
:tada:
