### ISSUE TITLE
Streaming download api without callback

### ISSUE THREAD

**Issue by jettify** [pohmelie/aioftp#8]
How about following api for file download:

```python
stream = yield from ftp.download_stream("foo.py", ...)
chunk = yield from stream.read(4096)
while chunk:
    chunk = yield from stream.read(4096)
    process(chunk)
```

similar what aiohttp does: http://aiohttp.readthedocs.org/en/latest/client.html#streaming-response-content

Should be very easy to implement.

**Comment by pohmelie** [comment]
Great idea! Definetly this should be released :+1:

**Comment by jettify** [comment]
I need suspend reading while I process chunk of data and might do some context switches too, is any way to do this with current implementation?

**Comment by pohmelie** [comment]
Hm, I think no, except to subclass and override some functions. I will implement this today or tomorrow, so you can just wait a little :smile:
Callbacks are definetly bad solution here, in python with asyncio.

**Comment by jettify** [comment]
Yes I can subclass ``Client`` and expose StreamReader directly. 

I am interested in ftp client and aioftp has good code coverage and documentation but callbacs do not allow me to do proper context switches. So this stops me from using aioftp...

**Comment by pohmelie** [comment]
I have just pushed new client api, based on StreamIO, documentation will comming soon. Example:
```python
stream = yield from client.download_stream("filename.txt")
stream = yield from client.upload_stream("filename.txt")
stream = yield from client.append_stream("filename.txt")

while True:
    data = yield from stream.read(count)
    line = yield from stream.readline()
    yield from stream.write(data)
    
    if not data or not line:  # or you done with writing
        yield from stream.finish()
        break
```

**Comment by jettify** [comment]
Looks good. I will try to test

**Comment by jettify** [comment]
I have tested streams, so far they works. Thanks!
